name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.10  # Corrected version
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            mkdir -p test1
            cd test1
            touch tssssss.php
            git clone git@github.com:DimaGevko/Dima-Gevko.git
            echo 'Deployment successful to Digital Ocean'
